#!/bin/bash



function usage ()
{
  local usage="
Usage: $(basename $0) [COMMAND] [OPTIONS]

Commands:
  run                          Run rmud

Options:
  -i, --image <name>           Image name (for example: rmud/rmud:19.03.2
"
    echo "$usage"
}

function run ()
{
    [[ -z "$IMAGE" ]] && { echo "Please specify image name (--image rmud/rmud:...)"; exit 1; }

    echo "Starting: $IMAGE"
    docker run \
        -v "$(pwd)/../rmud-data":/rmud-data \
        -v "$(pwd)/../rmud-live":/rmud-live \
        -p 3040:3040 \
        -p 4040:4040 \
        --rm \
        "$IMAGE" \
        ./rmud
    echo "Stopped: $IMAGE"
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -i|--image)
            IMAGE="$2"
            shift 2
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ $# -ne 1 ]
then
    usage
    exit 1
fi

command="$1"

case $command in
    run)
        run
        ;;
    *)
        echo "Invalid command: $command"
        exit 1
esac

